export const ADD_USER_REQUEST = "ADD_USER_REQUEST" 
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS" 
export const ADD_USER_RESET = "ADD_USER_RESET" 
export const ADD_USER_FAIL = "ADD_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS" 