export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST" 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS" 
export const UPDATE_USER_RESET = "UPDATE_USER_RESET" 
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"

export const GET_USER_ATTENDANCE_REQUEST = "GET_USER_ATTENDANCE_REQUEST" 
export const GET_USER_ATTENDANCE_SUCCESS = "GET_USER_ATTENDANCE_SUCCESS" 
export const GET_USER_ATTENDANCE_FAIL = "GET_USER_ATTENDANCE_FAIL"

export const SEARCH_USER_ATTENDANCE_REQUEST = "SEARCH_USER_ATTENDANCE_REQUEST" 
export const SEARCH_USER_ATTENDANCE_SUCCESS = "SEARCH_USER_ATTENDANCE_SUCCESS" 
export const SEARCH_USER_ATTENDANCE_FAIL = "SEARCH_USER_ATTENDANCE_FAIL"

export const UPDATE_USER_ATTENDANCE_REQUEST = "UPDATE_USER_ATTENDANCE_REQUEST" 
export const UPDATE_USER_ATTENDANCE_SUCCESS = "UPDATE_USER_ATTENDANCE_SUCCESS" 
export const UPDATE_USER_ATTENDANCE_RESET = "UPDATE_USER_ATTENDANCE_RESET" 
export const UPDATE_USER_ATTENDANCE_FAIL = "UPDATE_USER_ATTENDANCE_FAIL" 

export const GET_USER_SINGLE_ATTENDANCE_REQUEST = "GET_USER_SINGLE_ATTENDANCE_REQUEST" 
export const GET_USER_SINGLE_ATTENDANCE_SUCCESS = "GET_USER_SINGLE_ATTENDANCE_SUCCESS" 
export const GET_USER_SINGLE_ATTENDANCE_FAIL = "GET_USER_SINGLE_ATTENDANCE_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS" 