export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST" 
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS" 
export const DELETE_USER_RESET = "DELETE_USER_RESET" 
export const DELETE_USER_FAIL = "DELETE_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS" 