export const CREATE_REVENUE_REQUEST = "CREATE_REVENUE_REQUEST" 
export const CREATE_REVENUE_SUCCESS = "CREATE_REVENUE_SUCCESS" 
export const CREATE_REVENUE_RESET = "CREATE_REVENUE_RESET" 
export const CREATE_REVENUE_FAIL = "CREATE_REVENUE_FAIL"


export const GET_ALL_REVENUE_REQUEST = "GET_ALL_REVENUE_REQUEST" 
export const GET_ALL_REVENUE_SUCCESS = "GET_ALL_REVENUE_SUCCESS" 
export const GET_ALL_REVENUE_FAIL = "GET_ALL_REVENUE_FAIL"

export const GET_ALL_REVENUE_LIST_REQUEST = "GET_ALL_REVENUE_LIST_REQUEST" 
export const GET_ALL_REVENUE_LIST_SUCCESS = "GET_ALL_REVENUE_LIST_SUCCESS" 
export const GET_ALL_REVENUE_LIST_FAIL = "GET_ALL_REVENUE_LIST_FAIL"

export const GET_CURRENT_MONTH_TOTAL_REVENUE_REQUEST = "GET_CURRENT_MONTH_TOTAL_REVENUE_REQUEST" 
export const GET_CURRENT_MONTH_TOTAL_REVENUE_SUCCESS = "GET_CURRENT_MONTH_TOTAL_REVENUE_SUCCESS" 
export const GET_CURRENT_MONTH_TOTAL_REVENUE_FAIL = "GET_CURRENT_MONTH_TOTAL_REVENUE_FAIL"