export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST" 
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS" 
export const UPDATE_USER_RESET = "UPDATE_USER_RESET" 
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL" 

export const GET_USER_REQUEST = "GET_USER_REQUEST" 
export const GET_USER_SUCCESS = "GET_USER_SUCCESS" 
export const GET_USER_FAIL = "GET_USER_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS" 